### ISSUE TITLE
Model Training Pipeline - ValidationDataLocation Output Value incorrect

### ISSUE THREAD

**Issue by zortx233** [aws-solutions/mlops-workload-orchestrator#32]
**Describe the bug**
In the `model_training_pipeline.py`, the ValidationDataLocation output is pointing to the training location, instead of the validation location. The description also mentions training data instead of validation data.

Snippet from `model_training_pipeline.py` 
```CfnOutput(
            self,
            id="ValidationDataLocation",
            value=f"https://s3.console.aws.amazon.com/s3/buckets/{self.assets_bucket_name.value_as_string}/{self.training_data.value_as_string}",
            description="Training data used by the training job",
        ).node.condition = self.validation_data_provided
```

**To Reproduce**
Run the provisionpipeline step with the pipeline_type = `model_training_builtin` and specify a `training_data` and `validation_data` field

**Expected behavior**
The ValidationDataLocation should show the validation file, not the training file.

**Please complete the following information about the solution:**
- [v2.2.0] Version: [e.g. v1.0.0]

- [us-east-2 ] Region: [e.g. us-east-1]
- [no] Was the solution modified from the version published on this repository?
- [no ] If the answer to the previous question was yes, are the changes available on GitHub?
- [N/A ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?

**Screenshots**
Validation row should point to the validation.csv file
![mlops-pipeline-bug](https://github.com/aws-solutions/mlops-workload-orchestrator/assets/5373963/63ea3c00-0208-4cab-a224-3543a5c02909)

**Additional context**
Looks like a copy+paste bug.

**Comment by ysdholak** [comment]
Hello @zortx233 , thank you for submitting the bug. I will look into it. Thanks

**Comment by ysdholak** [comment]
I can confirm this is a bug and will be addressed in the next release. Thank you. 

Closing this issue.
